# projecteuler.net
# code.google.com/p/projecteuler-solutions/wiki/ProjectEulerSolutions

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#  By starting with 1 and 2, the first 10 terms will be:
#     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#  find the sum of the even-valued terms.

require_relative 'helper'

def fibseq(upperLimit)
	seq = [1,2]
	while seq.last < upperLimit
		nextSeq = seq.last(2).reduce(:+)
		if nextSeq < upperLimit
			seq.push(nextSeq)
		else
			return seq
		end
	end
	seq
end

correctAnswer = 4613732
myAnswer = fibseq(4000000).select{ |i| i.even? }.reduce(:+)
printResult(myAnswer, correctAnswer)